### ISSUE TITLE
Issue with fibers causing build to fail

### ISSUE THREAD

**Issue by leedongwei** [aedm/minimeteor#30]
Hello, could you help me with this issue?

This build is failing on locally and on Docker Hub too. There were no modifications to the app since the last successful build (which was 5 months ago). The app uses Meteor v1.4.2.3, I've added the stacktrace from Docker Hub below.

```
[91m
# Build Meteor app
echo [minimeteor] Building Meteor app
+ echo [minimeteor] Building Meteor app
sudo -u user meteor build --directory /home/user/meteor-app
+ sudo -u user meteor build --directory /home/user/meteor-app
[0m
[91m
Unable to resolve some modules:

[0m
[91m  "node-zlib-backport" in
/home/user/app/node_modules/qrcode/node_modules/pngjs/lib/packer-sync.js
(web.browser)
[0m
[91m
[0m
[91mIf you notice problems related to these missing modules, consider running:

  meteor npm install --save node-zlib-backport

[0m
[minimeteor] Install bundle NPM dependencies

[91m
# Install NPM packages in the bundle
echo [minimeteor] Install bundle NPM dependencies
+ echo [minimeteor] Install bundle NPM dependencies
cd /home/user/meteor-app/bundle/programs/server
+ cd /home/user/meteor-app/bundle/programs/server
sudo -u user meteor npm install
+ sudo -u user meteor npm install
[0m
[91mnpm[0m
[91m WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
[0m

> fibers@1.0.15 install /home/user/meteor-app/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js


make: Entering directory '/home/user/meteor-app/bundle/programs/server/node_modules/fibers/build'

  CXX(target) Release/obj.target/fibers/src/fibers.o

[91m../src/fibers.cc: In function 'v8::Handle<v8::String> uni::NewLatin1String(v8::Isolate*, const char*)':
../src/fibers.cc:122:64: warning: 'static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)' is deprecated (declared at /home/user/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:2668): Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
[0m
[91m../src/fibers.cc: In function 'v8::Handle<v8::String> uni::NewLatin1Symbol(v8::Isolate*, const char*)':
../src/fibers.cc:126:64: warning: 'static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)' is deprecated (declared at /home/user/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:2668): Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
[0m
[91m../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::New(const Arguments&)':
../src/fibers.cc:433:99: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /home/user/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3831): Use maybe version [-Wdeprecated-declarations]
     return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                   ^
[0m
[91m../src/fibers.cc: In static member function 'static void Fiber::RunFiber(void**)':
../src/fibers.cc:621:14: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /home/user/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:8260): Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^
[0m
[91m../src/fibers.cc: In static member function 'static void Fiber::SetPoolSize(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)':
../src/fibers.cc:741:43: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated (declared at /home/user/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:9707): Use maybe version [-Wdeprecated-declarations]
    Coroutine::pool_size = value->ToNumber()->Value();
                                           ^
[0m
[91m../src/fibers.cc: In static member function 'static void Fiber::Init(v8::Handle<v8::Object>)':
../src/fibers.cc:793:72: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /home/user/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3164): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                                                                        ^
[0m
[91m../src/fibers.cc:794:87: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /home/user/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3164): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                                                                                       ^
../src/fibers.cc:795:84: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /home/user/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3164): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                                                                                    ^
[0m
  CXX(target) Release/obj.target/fibers/src/coroutine.o

  CC(target) Release/obj.target/fibers/src/libcoro/coro.o

  SOLINK_MODULE(target) Release/obj.target/fibers.node

  COPY Release/fibers.node

make: Leaving directory '/home/user/meteor-app/bundle/programs/server/node_modules/fibers/build'

Installed in `/home/user/meteor-app/bundle/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node`


> meteor-dev-bundle@0.0.0 install /home/user/meteor-app/bundle/programs/server
> node npm-rebuild.js


[91mevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[0m
[91mnpm ERR! code ELIFECYCLE
npm ERR! errno 1
[0m
[91mnpm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0m
[91m
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-03-15T15_30_29_983Z-debug.log
[0m
Removing intermediate container 31e0e39f3508

Removing intermediate container 6610174c1456

Removing intermediate container af41cdd263e4

Removing intermediate container 901b4336f2be

Removing intermediate container ccb8a5000bc6

The command '/bin/sh -c /minimeteor/onbuild.sh' returned a non-zero code: 1
```

**Comment by nalbina** [comment]
Having the same problem.

**Comment by leedongwei** [comment]
I tried a few other Meteor Dockerfile and found a really old version of `meteor-launchpad` works with Meteor v1.4.2.3. 

```
FROM jshimko/meteor-launchpad:v1.1.1
```

I'm not maintaining my Meteor apps any more, so this was a good enough solution for me, hope it helps someone. In any case, this was an awesome project during the peak of Meteor's popularity. @aedm thanks for the hard work! 👍

**Comment by talfco** [comment]
Had the same issue, running my rather outdated Meteor App (using 1.5x and node 4.8.4). Due to coffescript dependency, I cannot update Meteor to newer version (1.7 issue). So I had to try another image and found abernix/meteord which provides a long list of tagged images which maps to node version installed in the image. By using "FROM abernix/meteord:node-4.8.4-onbuild" it worked out immediately. Can't figure out why this fails here. The minimeteor image uses the meteor npm... command so I would expect that this should have the same effect.
